"use client";

import { useEffect, useState } from "react";
import type { Language } from "@/i18n";
import type { Milestone, MilestoneCategory, MonthlyNote, PlayTip, WatchOut } from "./types";
import { CATEGORY_ORDER } from "./constants";

/** Everything the app shows for one month in one language (generated by scripts/split-content.mjs). */
export interface MonthContent {
  month: number;
  milestones: Milestone[];
  playTips: PlayTip[];
  watchOuts: WatchOut[];
  note: MonthlyNote | null;
}

export type MonthBundle = Record<Language, MonthContent>;

const cache = new Map<string, MonthContent>();
const inflight = new Map<string, Promise<MonthContent>>();

export function loadMonth(lang: Language, month: number): Promise<MonthContent> {
  const key = `${lang}/${month}`;
  const hit = cache.get(key);
  if (hit) return Promise.resolve(hit);
  let p = inflight.get(key);
  if (!p) {
    p = import(`@/content/gen/${lang}/${month}.json`).then((mod) => {
      const data = (mod.default ?? mod) as MonthContent;
      cache.set(key, data);
      inflight.delete(key);
      return data;
    });
    inflight.set(key, p);
  }
  return p;
}

/** Month content for the current language; null until the chunk is loaded (usually a few ms). */
export function useMonthContent(month: number, lang: Language): MonthContent | null {
  const key = `${lang}/${month}`;
  const [state, setState] = useState<{ key: string; data: MonthContent } | null>(null);
  useEffect(() => {
    let alive = true;
    loadMonth(lang, month).then((data) => {
      if (alive) setState({ key, data });
    });
    return () => {
      alive = false;
    };
  }, [key, lang, month]);
  return state && state.key === key ? state.data : null;
}

export function byCategory(milestones: Milestone[]): Record<MilestoneCategory, Milestone[]> {
  const out = { social: [], language: [], cognitive: [], physical: [] } as Record<MilestoneCategory, Milestone[]>;
  for (const cat of CATEGORY_ORDER) out[cat] = milestones.filter((m) => m.category === cat);
  return out;
}
