# Baby Growth Book brand system — five package definitions. Single source of truth.
# Every hex here must pass _build/qa.py (contrast in light AND dark); books and app mocks paint via tokens only.

# Tab glyphs (24-grid strokes) shared by every package — one icon library, no emoji.
GLYPHS = {
    "home":   '<path d="M3 11l9-8 9 8v9a1 1 0 0 1-1 1h-5v-6h-6v6H4a1 1 0 0 1-1-1z"/>',
    "flag":   '<path d="M5 3v18M5 4h12l-2 4 2 4H5"/>',
    "blocks": '<path d="M4 13h7v7H4zM13 13h7v7h-7zM8.5 4l3.5 6h-7z"/>',
    "shield": '<path d="M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z"/>',
    "book":   '<path d="M5 3h13v18H8a3 3 0 0 1-3-3zM5 18a3 3 0 0 1 3-3h10"/>',
    "check":  '<path d="M5 12l4 4 10-10"/>',
    "alert":  '<path d="M12 3l10 18H2zM12 10v5M12 18v.5"/>',
    "gear":   '<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1L7 17M17 7l2.1-2.1"/>',
    "plus":   '<path d="M12 5v14M5 12h14"/>',
    "chev":   '<path d="M9 6l6 6-6 6"/>',
}

# The Korean row that must render on every surface (bilingual reality check).
KO_ROW = "엄마 아빠 목소리를 알아요"
EN_ROW = "Recognizes parent's voice"

BRANDS = [
 dict(id="b01-dodam", name="Dodam", name_ko="도담", order="01", tag="Hanji and seal",
  essence=("도담도담 — the Korean word for a child growing up sturdy and well. Hanji cream, pine-green ink, and one "
           "cinnabar seal. Each milestone a parent confirms is stamped, the way a passbook is stamped: a quiet, "
           "physical record of a child growing well. Korean and English are one voice, not a translation."),
  tagline="Grow well, one month at a time.", tagline_ko="한 달 한 달, 도담도담.",
  # light
  bg="#FAF6EE", surface="#FFFCF6", ink="#1F3327", muted="#5F6356", primary="#2F5D45", on_primary="#FAF6EE",
  accent="#A63D2A", ornament="#C9453A", done="#C9453A", danger="#8C2F1F", caution="#7D5F16", info="#2F5D45",
  rule="#E6DFD0", hover="#F3EDE0",
  # dark
  d_bg="#151A16", d_surface="#1D231E", d_ink="#ECE7DA", d_muted="#A9AA9B", d_primary="#8CC1A2", d_on_primary="#10150F",
  d_accent="#E7967F", d_ornament="#E05C4E", d_done="#E05C4E", d_danger="#E68A79", d_caution="#D9B45B", d_info="#8CC1A2",
  d_rule="#2D342E", d_hover="#242B25",
  radius="12px", row="52px",
  f_display="Noto Serif KR", f_ui='-apple-system, BlinkMacSystemFont, "SF Pro Text", "Apple SD Gothic Neo", "Pretendard", "Noto Sans KR", system-ui, sans-serif',
  gf="family=Noto+Serif+KR:wght@500;600;700&family=Noto+Sans+KR:wght@400;500;600",
  wordmark_css="font-family:'Noto Serif KR',serif;font-weight:600;letter-spacing:-.01em;",
  mark_device="the seal (도장) — a square stamp holding ㄷ, the first letter of 도담 and a D at once",
  mark=('<rect x="4" y="4" width="24" height="24" rx="5" fill="none" stroke="{c}" stroke-width="2.4"/>'
        '<path d="M20 11H12v10h8" fill="none" stroke="{c}" stroke-width="2.8" stroke-linecap="square"/>'),
  icon_bg="#C9453A", icon_fg="#FAF6EE",
  icon=('<path d="M640 352H384v320h256" fill="none" stroke="{fg}" stroke-width="88" stroke-linecap="square"/>'),
  voice="A calm, literate grandmother who has raised children and reads the research. Warm, never cute. Says the true thing gently.",
  vx_done="Stamped. First smile, day 41.", vx_done_ko="도장 쾅. 첫 미소, 41일째.",
  vx_empty="The book is open. Write down one small thing from today.", vx_empty_ko="책이 펼쳐져 있어요. 오늘의 작은 일 하나를 적어 주세요.",
  vx_urgent="Back to sleep, every sleep. This one is not optional.", vx_urgent_ko="잠은 언제나 등을 대고. 이건 꼭 지켜 주세요.",
  app=[("Canvas","One column, 16pt gutters; hanji cream page, warm white cards; no pure white, no pure black."),
       ("Lists","52pt rows; the seal replaces the checkbox — empty outline before, cinnabar stamp after."),
       ("Type","Noto Serif KR for the wordmark and screen titles (both scripts); SF Pro / Apple SD Gothic Neo for everything else."),
       ("Controls","12pt radius, pine fill, cream text; secondary is a pine outline; destructive is oxblood text, never a red fill."),
       ("Motion","The stamp lands: 120ms scale from 1.15 to 1.0. Nothing else moves.")],
  ios="Tab bar of five with SF-style glyphs; large title uses the serif; safe areas honoured; the stamp is the haptic moment (light impact).",
  do_=["Stamp, don't tick — the seal is the whole brand","Write KO and EN as one voice","Keep cinnabar for the seal and the app icon only","Let hanji cream be the page; cards are warm white"],
  dont=["No pastel pink-and-blue baby clichés","No pure white, no pure black","No cinnabar text — it is an ornament, not an ink","No exclamation marks in system copy"],
  kr="Native. Apple SD Gothic Neo on iOS, Pretendard on the web (CDN), Noto Sans KR as the last fallback. Serif KR for titles in both scripts."),

 dict(id="b02-moons", name="Moons", name_ko="달", order="02", tag="Thirty-six moons",
  essence=("A month is a moon. The book is thirty-six of them. Ivory page, indigo ink, and a moon that fills gold as "
           "the month's milestones are met. Quiet and observational — the voice of someone who keeps a night diary."),
  tagline="Thirty-six moons, one small person.", tagline_ko="서른여섯 번의 달, 한 아이.",
  bg="#F7F5EE", surface="#FFFFFF", ink="#1B2233", muted="#5B6170", primary="#24325A", on_primary="#F7F5EE",
  accent="#6E5310", ornament="#D4AA3F", done="#D4AA3F", danger="#9B2F2F", caution="#6E5310", info="#24325A",
  rule="#E3E0D6", hover="#EFECE3",
  d_bg="#0F1422", d_surface="#171D2E", d_ink="#ECEBE3", d_muted="#A0A4B0", d_primary="#A9B8E8", d_on_primary="#0F1422",
  d_accent="#E2C46B", d_ornament="#E2C46B", d_done="#E2C46B", d_danger="#F09090", d_caution="#E2C46B", d_info="#A9B8E8",
  d_rule="#262D40", d_hover="#1E2537",
  radius="16px", row="52px",
  f_display="Fraunces", f_ui='-apple-system, BlinkMacSystemFont, "SF Pro Text", "Apple SD Gothic Neo", "Pretendard", "Noto Sans KR", system-ui, sans-serif',
  gf="family=Fraunces:opsz,wght@9..144,500;9..144,600&family=Noto+Sans+KR:wght@400;500;600",
  wordmark_css="font-family:'Fraunces',serif;font-weight:500;letter-spacing:.01em;",
  mark_device="the phase disc — a crescent that becomes a full moon as the month completes",
  mark=('<path fill-rule="evenodd" d="M16 4a12 12 0 1 0 0 24 12 12 0 1 0 0-24zm4 2a10 10 0 1 1 0 20 10 10 0 1 1 0-20z" fill="{c}"/>'),
  icon_bg="#24325A", icon_fg="#D4AA3F",
  icon=('<path fill-rule="evenodd" d="M512 176a336 336 0 1 0 0 672 336 336 0 1 0 0-672zm120 56a280 280 0 1 1 0 560 280 280 0 1 1 0-560z" fill="{fg}"/>'),
  voice="A night diarist. Notices, records, does not fuss.",
  vx_done="Moon 3, waxing. Rolled over today.", vx_done_ko="세 번째 달. 오늘 처음 뒤집었어요.",
  vx_empty="No entries yet this moon.", vx_empty_ko="이번 달에는 아직 기록이 없어요.",
  vx_urgent="Button batteries burn in two hours. Keep every remote out of reach.", vx_urgent_ko="단추 전지는 두 시간이면 화상을 입혀요. 리모컨은 손이 닿지 않는 곳에 두세요.",
  app=[("Canvas","One column; ivory page, white cards, indigo type; the moon lives in the header."),
       ("Lists","52pt rows; a small disc fills from crescent to full as the row is confirmed."),
       ("Type","Fraunces for wordmark and month numerals; system faces for UI in both scripts."),
       ("Controls","16pt radius, indigo fill, ivory text; gold only for the disc and the today marker."),
       ("Motion","The disc fills over 200ms. Nothing else moves.")],
  ios="Five tabs; the month header shows the phase disc at large title size; dark mode is the brand's native state.",
  do_=["One moon per screen, maximum","Use gold for the disc only","Set month numerals in Fraunces","Keep copy in the past tense — things observed"],
  dont=["No stars, no night-sky gradients","No gold text on ivory — it fails contrast by design","No exclamation marks","Never show two discs side by side"],
  kr="Apple SD Gothic Neo / Pretendard for UI; Fraunces carries Latin numerals only — Korean month labels set in the UI face."),

 dict(id="b03-sprout", name="Sprout", name_ko="새싹", order="03", tag="Warm coral, evolved",
  essence=("The current identity, matured: terracotta rather than coral, cream rather than white, and the two-leaf "
           "sprout kept as the only picture in the system. Friendly and upbeat; the safest of the five and the "
           "least distinctive — a name already used by several baby apps."),
  tagline="Grow, one leaf at a time.", tagline_ko="한 잎, 한 잎 자라요.",
  bg="#FFF8F3", surface="#FFFFFF", ink="#3A2A22", muted="#6F5D52", primary="#B0432A", on_primary="#FFF8F3",
  accent="#B0432A", ornament="#E86F4A", done="#2E7A45", danger="#A0301E", caution="#8A5E10", info="#3E5F8C",
  rule="#F0DED2", hover="#FBEDE4",
  d_bg="#1C1512", d_surface="#261D18", d_ink="#F5E9E1", d_muted="#B8A79C", d_primary="#F2917A", d_on_primary="#1C1512",
  d_accent="#F2917A", d_ornament="#F2917A", d_done="#8FCB9B", d_danger="#F09A8A", d_caution="#E0B860", d_info="#9FBCE8",
  d_rule="#3A2C25", d_hover="#302420",
  radius="20px", row="56px",
  f_display="Nunito", f_ui='-apple-system, BlinkMacSystemFont, "SF Pro Text", "Apple SD Gothic Neo", "Pretendard", "Noto Sans KR", system-ui, sans-serif',
  gf="family=Nunito:wght@600;700;800&family=Noto+Sans+KR:wght@400;500;600",
  wordmark_css="font-family:'Nunito',sans-serif;font-weight:800;letter-spacing:-.02em;",
  mark_device="the two-leaf sprout",
  mark=('<path d="M16 28V14" stroke="{c}" stroke-width="2.6" stroke-linecap="round" fill="none"/>'
        '<path d="M16 16c-1-6-5-8-10-8 0 6 4 9 10 8z" fill="{c}"/><path d="M16 12c1-5 4-7 9-7 0 5-3 8-9 7z" fill="{c}"/>'),
  icon_bg="#E86F4A", icon_fg="#FFF8F3",
  icon=('<path d="M512 880V440" stroke="{fg}" stroke-width="72" stroke-linecap="round" fill="none"/>'
        '<path d="M512 520c-30-190-160-250-320-250 0 190 130 290 320 250z" fill="{fg}"/><path d="M512 400c30-160 130-220 290-220 0 160-100 250-290 220z" fill="{fg}"/>'),
  voice="An encouraging friend who has been through it. Upbeat, plain, kind.",
  vx_done="Nice — first smile logged.", vx_done_ko="좋아요. 첫 미소 기록 완료.",
  vx_empty="Nothing here yet. Start with today.", vx_empty_ko="아직 아무것도 없어요. 오늘부터 시작해요.",
  vx_urgent="Back to sleep, every single time.", vx_urgent_ko="잠은 언제나 등을 대고 재워요.",
  app=[("Canvas","One column; cream page, white cards, generous 20pt radius."),
       ("Lists","56pt rows; the leaf fills green when confirmed."),
       ("Type","Nunito for the wordmark and titles; system faces for body in both scripts."),
       ("Controls","Pill buttons, terracotta fill, cream text."),
       ("Motion","Leaf unfolds 180ms on confirm.")],
  ios="Five tabs; rounded, friendly, familiar to anyone who has used a consumer health app.",
  do_=["Keep the sprout as the only illustration","Use green for done only","Cream page, white cards","Short, cheerful sentences"],
  dont=["No gradients on the icon (the current one has two)","No sparkle or star motifs","No additional mascots","No coral body text"],
  kr="Apple SD Gothic Neo / Pretendard for UI; Nunito carries Latin titles, Korean titles set in the UI face at 700."),

 dict(id="b04-firsts", name="Firsts", name_ko="처음", order="04", tag="A book of firsts",
  essence=("Every milestone is a first. The app is a ledger of them: paper white, black ink, and one red circle — "
           "the mark a parent draws around a date. Editorial and exact; entries read like a dated record."),
  tagline="Every first, written down.", tagline_ko="모든 처음을 적어 두는 책.",
  bg="#FFFFFF", surface="#F7F7F5", ink="#111111", muted="#595959", primary="#111111", on_primary="#FFFFFF",
  accent="#A8241C", ornament="#D0342C", done="#D0342C", danger="#111111", caution="#6E5310", info="#595959",
  rule="#E5E5E2", hover="#F2F2F0",
  d_bg="#121212", d_surface="#1B1B1B", d_ink="#F2F2F2", d_muted="#A6A6A6", d_primary="#F2F2F2", d_on_primary="#121212",
  d_accent="#FF8A80", d_ornament="#FF5C51", d_done="#FF5C51", d_danger="#F2F2F2", d_caution="#E3BE62", d_info="#A6A6A6",
  d_rule="#2A2A2A", d_hover="#222222",
  radius="4px", row="48px",
  f_display="Newsreader", f_ui='-apple-system, BlinkMacSystemFont, "SF Pro Text", "Apple SD Gothic Neo", "Pretendard", "Noto Sans KR", system-ui, sans-serif',
  gf="family=Newsreader:opsz,wght@6..72,500;6..72,600&family=Noto+Serif+KR:wght@500;600&family=Noto+Sans+KR:wght@400;500;600",
  wordmark_css="font-family:'Newsreader',serif;font-weight:500;letter-spacing:.02em;text-transform:uppercase;",
  mark_device="the circled first — a hand-drawn ring around a numeral",
  mark=('<circle cx="16" cy="16" r="12" fill="none" stroke="{c}" stroke-width="2.4"/>'
        '<path d="M12.5 11.5 16.5 8.5V23.5M13 23.5h7" fill="none" stroke="{c}" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/>'),
  icon_bg="#FFFFFF", icon_fg="#D0342C",
  icon=('<circle cx="512" cy="512" r="360" fill="none" stroke="{fg}" stroke-width="64"/>'
        '<path d="M420 420l100-80v380M440 720h190" fill="none" stroke="#111111" stroke-width="72" stroke-linecap="round" stroke-linejoin="round"/>'),
  voice="A documentarian. Dates everything. No adjectives it cannot defend.",
  vx_done="First smile. Day 41. Circled.", vx_done_ko="첫 미소. 41일째. 표시함.",
  vx_empty="No entries. The first one is the hardest to start.", vx_empty_ko="기록이 없어요. 첫 줄이 가장 어렵죠.",
  vx_urgent="Safe sleep is a rule, not advice: back, flat, bare crib.", vx_urgent_ko="안전한 잠은 조언이 아니라 규칙이에요. 등을 대고, 평평하게, 빈 침대에.",
  app=[("Canvas","White page, light-grey cards, hairline rules; the list is the page."),
       ("Lists","48pt rows; confirming draws the red ring around the row's number."),
       ("Type","Newsreader for wordmark and titles (Noto Serif KR in Korean); system faces for UI."),
       ("Controls","4pt radius, black fill, white text; the red is never a fill."),
       ("Motion","The ring draws on in 240ms (stroke-dashoffset). Nothing else moves.")],
  ios="Five tabs in black glyphs; large titles in the serif; dark mode inverts paper and ink, red stays.",
  do_=["Date every entry","Draw the ring — never a tick","Let whitespace group","Keep danger in black; red belongs to the record"],
  dont=["No colour beyond ink, paper and the ring","No rounded buttons","No decorative serifs in body text","No cheer — the record is the reward"],
  kr="Noto Serif KR mirrors Newsreader for Korean titles; Apple SD Gothic Neo / Pretendard for UI."),

 dict(id="b05-nabi", name="Nabi", name_ko="나비", order="05", tag="Butterfly",
  essence=("나비, butterfly: a child changes shape month by month. Pale sky page, plum ink, a mustard wing. Light and "
           "playful without being childish — geometric wings drawn from two arcs, never a cartoon."),
  tagline="A little different every month.", tagline_ko="매달 조금씩 달라져요.",
  bg="#F6F8FB", surface="#FFFFFF", ink="#2A2140", muted="#5F5A6E", primary="#5B3D8C", on_primary="#F6F8FB",
  accent="#6E5300", ornament="#E9B949", done="#E9B949", danger="#9C2B4B", caution="#6E5300", info="#5B3D8C",
  rule="#E1E5EE", hover="#EDF0F6",
  d_bg="#14121C", d_surface="#1D1A28", d_ink="#EEEBF5", d_muted="#A9A4B8", d_primary="#C3A9F0", d_on_primary="#14121C",
  d_accent="#F0CC6A", d_ornament="#F0CC6A", d_done="#F0CC6A", d_danger="#F08AA8", d_caution="#F0CC6A", d_info="#C3A9F0",
  d_rule="#2C2838", d_hover="#241F31",
  radius="18px", row="52px",
  f_display="Outfit", f_ui='-apple-system, BlinkMacSystemFont, "SF Pro Text", "Apple SD Gothic Neo", "Pretendard", "Noto Sans KR", system-ui, sans-serif',
  gf="family=Outfit:wght@500;600;700&family=Noto+Sans+KR:wght@400;500;600",
  wordmark_css="font-family:'Outfit',sans-serif;font-weight:600;letter-spacing:.04em;text-transform:lowercase;",
  mark_device="the two-arc wing",
  mark=('<path d="M16 16C16 8 10 4 5 6c-1 6 3 11 11 10z" fill="{c}"/><path d="M16 16c0-8 6-12 11-10 1 6-3 11-11 10z" fill="{c}"/>'
        '<path d="M16 17c-1 5-5 8-9 7 0-5 4-8 9-7z" fill="{c}" opacity=".7"/><path d="M16 17c1 5 5 8 9 7 0-5-4-8-9-7z" fill="{c}" opacity=".7"/>'
        '<path d="M16 12v14" stroke="{c}" stroke-width="2" stroke-linecap="round" fill="none"/>'),
  icon_bg="#5B3D8C", icon_fg="#E9B949",
  icon=('<path d="M512 512c0-250-190-380-350-320-30 190 100 350 350 320z" fill="{fg}"/><path d="M512 512c0-250 190-380 350-320 30 190-100 350-350 320z" fill="{fg}"/>'
        '<path d="M512 544c-30 160-160 250-290 220 0-160 130-250 290-220z" fill="{fg}" opacity=".75"/><path d="M512 544c30 160 160 250 290 220 0-160-130-250-290-220z" fill="{fg}" opacity=".75"/>'),
  voice="A playful aunt. Light, curious, quick to notice.",
  vx_done="New wing: first smile, day 41.", vx_done_ko="새 날개. 첫 미소, 41일째.",
  vx_empty="Empty so far. What did you notice today?", vx_empty_ko="아직 비어 있어요. 오늘은 뭘 발견했나요?",
  vx_urgent="Back to sleep, every time — this one has no exceptions.", vx_urgent_ko="잠은 언제나 등을 대고. 예외는 없어요.",
  app=[("Canvas","One column; sky page, white cards, 18pt radius."),
       ("Lists","52pt rows; the wing fills mustard when confirmed."),
       ("Type","Outfit for wordmark and titles; system faces for UI in both scripts."),
       ("Controls","18pt radius, plum fill, sky text; mustard only for the wing."),
       ("Motion","Wings open 200ms on confirm.")],
  ios="Five tabs; playful glyphs; large title in Outfit; dark mode deepens plum, mustard stays.",
  do_=["Draw wings from arcs only","Keep mustard for the wing","Short, curious sentences","Plum for action only"],
  dont=["No cartoon butterflies or antennae","No pastel rainbows","No mustard text on sky — it fails contrast","No more than one wing per screen"],
  kr="Apple SD Gothic Neo / Pretendard for UI; Outfit carries Latin titles; Korean titles in the UI face at 600."),
]

# Five milestone rows used in every sample list (EN title, KO title, done?)
ROWS = [
    (EN_ROW, KO_ROW, True),
    ("Makes eye contact during feeding", "수유할 때 눈을 맞춰요", True),
    ("Startles at loud sounds", "큰 소리에 깜짝 놀라요", False),
    ("Focuses on faces", "얼굴을 가만히 바라봐요", False),
    ("Lifts head briefly during tummy time", "엎드리면 잠깐 고개를 들어요", False),
]
